site_name: 'onboarding-docs'
repo_url: https://github.com/karsingh15/app-customer-onboarding
edit_uri: edit/master/docs

nav:
  # relative reference to your Markdown file and an optional title
  - Onboarding: index.md
  
markdown_extensions:
  - markdown_inline_mermaid
  
plugins:
  - techdocs-core
