site_name: 'onboarding-docs'
repo_url: https://github.com/karsingh15/app-customer-onboarding
edit_uri: edit/master/docs

nav:
  # relative reference to your Markdown file and an optional title
  - Onboarding: index.md
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
plugins:
  - techdocs-core
