apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-customer-registration
  # This is an extra long description with Markdown
  description: |
    These are the customer registration services that hold the actual business logic. These services are identified based on the business capabilities through domain driven design.
  links:
   - url: https://github.com/karsingh15/app-customer-onboarding/tree/master/app-customer-registration
     title: Github Repo
     icon: github
  annotations:
    sonarqube.org/project-key: domain-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  system: app-customer-onboarding
  owner: onboarding-team
  tags: v0.1.1
  providesApis:
    - api-customer-registration
